Script to automate the local test procedure - keeps the local test ta…
citycoins/protocol pull request #42
Opened 2023-01-03 18:25 UTC by radicleart

Script to keep the local test target contracts in sync with the deployed contracts. Copies and filters the relevant contracts to the `test` directory and copies the Clarinet.local.toml file to Clarinet.toml for local testing.

2023-01-03 23:22 UTC, whoabuddy requested changes
Overall this looks great! Created #43 with some updated formatting and fixes which can be merged back into this PR if you approve. 

With the comments there were two main items:

1. what happens when I want to change back to default?
2. Clarinet.local.toml and Clarinet.default.toml have fallen out of sync
  - they should contain the same contracts where possible
  - they should be clearly commented if one is not supported

2023-01-03 23:22 UTC, whoabuddy commented on Clarinet.local.toml
> +[contracts.ccd009-auth-v2-adapter]
Should this contract be listed in `Clarinet.default.toml` as well?

2023-01-03 23:22 UTC, whoabuddy commented on README.md
> +To automate the above strategy;
What if I want to go back to the default config? Do I manually copy the file?

2023-01-03 23:22 UTC, whoabuddy commented on README.md
> +`clarinet.toml`. To make the script executable in your environment run
Rewrote this to be a bit clearer:

```suggestion
This script will copy and filter the mining and stacking contracts to create local copies
with local contract references, as well as copy `clarinet.local.toml` to `clarinet.toml`. 
```

2023-01-03 23:22 UTC, whoabuddy commented on README.md
> +```
Moved this text to be with the command as a separate item.

```suggestion
If you are unable to execute the script, run the following command to update the permissions then try again:

```bash
chmod 755 scripts/copy-contracts.sh
```
```

2023-01-03 23:22 UTC, whoabuddy commented on README.md
> +scripts/copy-contracts.sh
Shouldn't we specify using bash here since it's a bash script? (that's how I ran it!)

```suggestion
bash scripts/copy-contracts.sh
```

2023-01-03 23:28 UTC, whoabuddy commented
Also confirming the development flow with this in place:

1. make updates to ccd006 (or any default/local enabled contract)
2. run script to sync changes with local ccd006 and replace names
3. run clarinet check and test based on the code revisions

Are there any considerations needed for the models or tests as well?

If I'm creating a new ccd006 mining test, does it go in the `tests/extensions` directory by default, unless it has to interact with a localized contract?

`tests/extensions/ccd006-city-mining.test.ts`
vs
`tests/extensions/local/ccd006-city-mining.test.ts`

2023-01-04 20:17 UTC, radicleart commented
Thinking about this @whoabuddy. 

The local test set _extends_ the default set - i.e. the default set is run in its entirety whenever we run the local set. Is there any reason to support the Clarinet.default.toml version given we've now codified the rules for generating the local contracts in the bash script ? I.e couldn't we just say the complete set of tests needs to be run every time?

2023-01-04 21:00 UTC, whoabuddy commented
The thing we'll have to watch out for is the possibility of someone committing changes to the main contracts without remembering to run the script.

In the previous config I wouldn't see Clarity LSP updates unless I was working in the local version - so we'd need to check on that as well. I'd start on something for ccd006, copy it to local, *then realize* clarinet check was complaining about something.

We could setup automation but a pre-commit hook wouldn't work for Windows by default (no `bash` without WSL) and having another tool to check if this update was made sounds a bit overkill.

For now it makes sense to go with the idea of simplifying as long as it provides a consistent experience. The current setup left some confusion on where to make contract updates and which file to add tests to, but I still think this is a step in a better direction!

2023-01-05 14:30 UTC, radicleart commented
I just just the changes I think make sense - feel free to roll them back - hopefully the updated README provides a good enough justification for leaving it.

2023-01-05 15:40 UTC, whoabuddy commented
It makes sense and looks good, I think we're getting closer to a solution here!

The one thing that jumps out at me is the default contracts aren't in the Clarinet.toml, so if something goes funny with the copy, or if something is overwritten on accident, those changes could be committed without Clarinet being able to check/test against them.

What if we just list the default and local contracts in the toml with different names? Then we know all the contracts are listed in one file, e.g.

```toml
[contracts.ccd006-city-mining]
path = "contracts/extensions/ccd006-city-mining.clar"

[contracts.ccd006-city-mining-local]
path = "tests/contracts/extensions/ccd006-city-mining.clar"

[contracts.ccd007-city-stacking]
path = "contracts/extensions/ccd007-city-stacking.clar"

[contracts.ccd007-city-stacking-local]
path = "tests/contracts/extensions/ccd007-city-stacking.clar"
```

Since the testing models accept a string as the name we can take a similar approach to the treasury contracts, where both the default/local contracts comply with ccd006.

That way everything is run against clarinet check, and the test files then represent which contract they're interacting with:

- `tests/extensions/ccd006-city-mining.test.ts` would use `ccd006-city-mining`
- `tests/local/extensions/ccd006-city-mining.test.ts` would use `ccd006-city-mining-local`

We'd still need the bash script for syncing up the two and development would still flow from default -> local based on the script operation. What do you think?

2023-01-05 15:50 UTC, whoabuddy requested changes
Found a few small things but this is looking good!

Great questions to ask now and set a precedent for moving forward.

2023-01-05 15:50 UTC, whoabuddy commented on README.md
> +NB If you are unable to execute the script, run the following command to update the permissions then try again:
What's `NB` in this context?

2023-01-05 15:50 UTC, whoabuddy commented on README.md
> +```
Noting this part might change pending convo here: https://github.com/citycoins/protocol/pull/42#issuecomment-1372381619

2023-01-05 15:50 UTC, whoabuddy commented on README.md
> +and these tests would be expected to fail if the Clarinet.toml was switched back to the default.
No more default/local version :)

2023-01-05 15:50 UTC, whoabuddy commented on scripts/copy-contracts.sh
> +cp Clarinet.local.toml Clarinet.toml
Should these lines be removed?

2023-01-05 16:02 UTC, radicleart commented on scripts/copy-contracts.sh
> +cp Clarinet.local.toml Clarinet.toml
will do.

2023-01-05 18:10 UTC, whoabuddy approved these changes
lgtm thank you!

2023-01-05 18:10 UTC, merged