CCIP-021: Extend Direct Execution Sunset Period
citycoins/protocol pull request #69
Opened 2024-04-04 20:15 UTC by friedger

This PR
* implements CCIP-021 defined at https://github.com/citycoins/governance/pull/31

2024-04-05 04:10 UTC, whoabuddy requested changes
Found a few things but overall looks great, thank you!

2024-04-05 04:10 UTC, whoabuddy commented on contracts/proposals/ccip021-extend-sunset-period-2.clar
> +)
Update for cycles 80/81

```suggestion
(define-read-only (get-mia-vote (cityId uint) (userId uint) (scaled bool))
  (let
    (
      ;; MAINNET: MIA cycle 80 / first block BTC 834,050 STX 142,301
      ;; cycle 2 / u4500 used in tests
      (cycle80Hash (unwrap! (get-block-hash u4500) none))
      (cycle80Data (at-block cycle80Hash (contract-call? .ccd007-citycoin-stacking get-stacker cityId u2 userId)))
      (cycle80Amount (get stacked cycle80Data))
      ;; MAINNET: MIA cycle 81 / first block BTC 836,150 STX 143,989
      ;; cycle 3 / u6600 used in tests
      (cycle81Hash (unwrap! (get-block-hash u6600) none))
      (cycle81Data (at-block cycle81Hash (contract-call? .ccd007-citycoin-stacking get-stacker cityId u3 userId)))
      (cycle81Amount (get stacked cycle81Data))
      ;; MIA vote calculation
      (avgStacked (/ (+ (scale-up cycle80Amount) (scale-up cycle81Amount)) u2))
      (scaledVote (/ (* avgStacked MIA_SCALE_FACTOR) MIA_SCALE_BASE))
    )
    ;; check that at least one value is positive
    (asserts! (or (> cycle80Amount u0) (> cycle81Amount u0)) none)
    ;; return scaled or unscaled value
    (if scaled (some scaledVote) (some (/ scaledVote VOTE_SCALE_FACTOR)))
  )
)
```

2024-04-05 04:10 UTC, whoabuddy commented on contracts/proposals/ccip021-extend-sunset-period-2.clar
> +)
Update for cycles 80/81

```suggestion
(define-read-only (get-nyc-vote (cityId uint) (userId uint) (scaled bool))
  (let
    (
      ;; NYC cycle 80 / first block BTC 834,050 STX 142,301
      ;; cycle 2 / u4500 used in tests
      (cycle80Hash (unwrap! (get-block-hash u4500) none))
      (cycle80Data (at-block cycle80Hash (contract-call? .ccd007-citycoin-stacking get-stacker cityId u2 userId)))
      (cycle80Amount (get stacked cycle80Data))
      ;; NYC cycle 81 / first block BTC 836,150 STX 143,989
      ;; cycle 3 / u6600 used in tests
      (cycle81Hash (unwrap! (get-block-hash u6600) none))
      (cycle81Data (at-block cycle81Hash (contract-call? .ccd007-citycoin-stacking get-stacker cityId u3 userId)))
      (cycle81Amount (get stacked cycle81Data))
      ;; NYC vote calculation
      (scaledVote (/ (+ (scale-up cycle80Amount) (scale-up cycle81Amount)) u2))
    )
    ;; check that at least one value is positive
    (asserts! (or (> cycle80Amount u0) (> cycle81Amount u0)) none)
    ;; return scaled or unscaled value
    (if scaled (some scaledVote) (some (/ scaledVote VOTE_SCALE_FACTOR)))
  )
)
```

2024-04-05 04:21 UTC, whoabuddy commented
Also see the change in #70 to pin the Clarinet version so the tests pass :)

2024-04-05 12:27 UTC, whoabuddy commented on contracts/proposals/ccip021-extend-sunset-period-2.clar
> +  hash: "", ;; TODO
Actually, it's generally the hash of the commit, e.g. below:
https://github.com/citycoins/governance/pull/31/commits/4e1734ef002105d5b787bb88fedacda4c0dccbf2

Which in the contract we would just use `4e1734ef002105d5b787bb88fedacda4c0dccbf2`.

2024-04-06 01:12 UTC, friedger commented on contracts/proposals/ccip021-extend-sunset-period-2.clar
> +  hash: "", ;; TODO
done

2024-04-06 13:30 UTC, whoabuddy approved these changes

2024-04-06 13:33 UTC, merged