Implement ccip016
citycoins/protocol pull request #83
Opened 2024-12-04 16:29 UTC by friedger

This PR
* adds a proposal that distributes missed payouts for mia stakers as defined in CCIP-016

2025-01-03 13:30 UTC, whoabuddy requested changes
Overall looks good! :pray: Left some feedback on what I saw in the review comments.

I would like to add some testing around the contract alongside the simulation, mostly to make sure the voting works as expected. Payout code looks clean/simple but will be important to make sure we can reproduce those numbers from the CCIP text/resources.

2025-01-03 13:30 UTC, whoabuddy commented on contracts/proposals/ccip016-missed-payouts.clar
> +  hash: "",
Noting that the [CCIP-016 governance text](https://github.com/citycoins/governance/blob/feat/add-ccip-016/ccips/ccip-016/ccip-016-refund-incorrect-ccd007-payouts.md) needs to be updated and hash can be added here.

2025-01-03 13:30 UTC, whoabuddy commented on contracts/proposals/ccip016-missed-payouts.clar
> +    (var-set voteEnd block-height)
We could set this one to be a true 2100 block / 2 week vote since we're not rushing to have it done by a block height. [CCIP-024 did the same thing](https://explorer.hiro.so/txid/SP8A9HZ3PKST0S42VM9523Z9NV42SZ026V4K39WH.ccip024-miamicoin-signal-vote?chain=mainnet).

If we do that we'd have to switch to tenure or burn block height, so maybe better to leave as-is? Block heights move fast now!

2025-01-03 13:30 UTC, whoabuddy commented on contracts/proposals/ccip016-missed-payouts.clar
> +  (try! (contract-call? 'SP8A9HZ3PKST0S42VM9523Z9NV42SZ026V4K39WH.ccd002-treasury-mia-stacking withdraw-stx u30487 'SP32VE3A2AXWPGT7HH4B76005TJZQK7CF1MM9R0MD))
I think we can set both these contract names as constants, e.g. `MIA_STACKING_TREASURY` and `NYC_STACKING_TREASURY` and use that with the payout function. Same thing just a bit shorter/easier to read.

2025-01-03 13:30 UTC, whoabuddy commented on contracts/proposals/ccip016-missed-payouts.clar
> +(define-private (pay-all-rewards)
Where are these calculations coming from? It'd be good to reference the source data in the CCIP text and resources, even better if it's easy for someone to reproduce the result.

2025-02-17 11:45 UTC, friedger commented on contracts/proposals/ccip016-missed-payouts.clar
> +(define-private (pay-all-rewards)
The code come from https://github.com/citycoins/scripts/pull/26

2025-04-15 12:00 UTC, friedger commented on contracts/proposals/ccip016-missed-payouts.clar
> +  (try! (contract-call? 'SP8A9HZ3PKST0S42VM9523Z9NV42SZ026V4K39WH.ccd002-treasury-mia-stacking withdraw-stx u30487 'SP32VE3A2AXWPGT7HH4B76005TJZQK7CF1MM9R0MD))
This is still an open issue: https://github.com/clarity-lang/reference/issues/77

2025-04-15 12:01 UTC, friedger commented on contracts/proposals/ccip016-missed-payouts.clar
> +  (try! (contract-call? 'SP8A9HZ3PKST0S42VM9523Z9NV42SZ026V4K39WH.ccd002-treasury-mia-stacking withdraw-stx u30487 'SP32VE3A2AXWPGT7HH4B76005TJZQK7CF1MM9R0MD))
Not possible today.

2025-05-10 08:01 UTC, friedger commented
Deployed at https://explorer.hiro.so/txid/0x79a3a2f32e163f4ceb1cd81e93808c25911a0a7fbe3b2facaa5c892c16a25045?chain=mainnet

2025-09-04 18:41 UTC, whoabuddy approved these changes

2025-09-04 18:41 UTC, merged